In [1]:
import pandas as pd
import numpy as np

# Load the Dataset

In [2]:
r_cols=['user_id','movie_id','rating','unix_timestamp']
rating=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')
# csv is comma separted value and '\t' is tab separated value
# u.data is a file
# u.data doesn't have a header row with columns names, so we created columns name as a list
# encoding ='latin-1' is converting characters into numbers and text.

In [3]:
rating

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

# Created a Column names in a list

In [4]:
n_user=rating.user_id.unique().shape[0]
n_items=rating.movie_id.unique().shape[0]
print("The number of user:",n_user)
print("The number of n_items:",n_items)
# unique() will delect all duplicate or reparated value in a row.
# shape[0] shape is total count of the row,0 means rows and 1 means columns.

The number of user: 943
The number of n_items: 1682

# Creating Pivot table for user and movie based on rating

In [5]:
datama=rating.pivot_table (index='user_id',columns='movie_id',values='rating')
# pivot_table is inbuild function  
# Create a pivot table for the unique values of users, movies, and their ratings to make it easier to read.

# Replace with nan with 0

In [6]:
data_matrix=datama.replace(np.nan,0)
# Filling nan values with 0

In [7]:
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Find Cosine Similarity for user and item

In [8]:
from sklearn.metrics.pairwise import pairwise_distances 
user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [9]:
user_similarity

array([[2.22044605e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 0.00000000e+00, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 0.00000000e+00, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

In [10]:
item_similarity

array([[0.00000000e+00, 5.97617822e-01, 6.69755213e-01, ...,
        1.00000000e+00, 9.52816933e-01, 9.52816933e-01],
       [5.97617822e-01, 0.00000000e+00, 7.26930825e-01, ...,
        1.00000000e+00, 9.21700637e-01, 9.21700637e-01],
       [6.69755213e-01, 7.26930825e-01, 2.22044605e-16, ...,
        1.00000000e+00, 1.00000000e+00, 9.03124947e-01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 9.03124947e-01, ...,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

# Using Formula for used and item we are calculating the score value

In [11]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        mean_user_rating_array = np.array(mean_user_rating)  # Convert to numpy array
        ratings_diff = (ratings - mean_user_rating_array[:, np.newaxis])
        pred = mean_user_rating_array[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

# Explanation for Score Value

In [12]:
# mean is find average 
# axis=1 is rows 
# [:,np.newaxis] - [:] is row, np.newaxis is adding a new axis to shape the array 
# dot - is weighted sum find weight value for similarity and ratings_diff
# np.abs - abs is absoule value convert the negative values into positive values 
# sum - total count value for the similarity row 
# T - Transpose Converting rows into columns and columns into rows

In [13]:
# 1. Finding mean value for rating 
# 2. Converting rating mean value into array 
# 3. Subrating rating mean array value from rating and adding new axis to it.
# 4. Finding weighted value for similarity and rating_diff
# 5. Adding rating mean array value with weighted values divided with absoule&sum of similarity and transposeing the similarity

# Prediction Table

In [14]:
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

In [15]:
user_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]])

In [16]:
item_prediction

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
2,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
3,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
4,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
5,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
940,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
941,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
942,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
943,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

# As per user based filtering,first have to find similarity between the input user and others

In [17]:
# Select input user
input_user=34

In [18]:
# Convert the user_similarity table into DataFrame
user_sim_table=pd.DataFrame(user_similarity)

In [19]:
user_sim_table

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.220446e-15,0.833069,0.952540,0.935642,6.215248e-01,0.569761,0.559633,0.680928,0.921862,0.623456,...,0.630473,0.880518,0.725124,0.810295,0.802674,0.881905,6.859280e-01,0.851383,0.820492,0.601825
1,8.330690e-01,0.000000,0.889409,0.821879,9.270210e-01,0.754157,0.892672,0.896656,0.838952,0.840138,...,0.843014,0.692058,0.641211,0.575954,0.680111,0.771417,7.732100e-01,0.838515,0.827732,0.894202
2,9.525405e-01,0.889409,0.000000,0.655849,9.787555e-01,0.927585,0.933863,0.916940,0.938960,0.934849,...,0.968125,0.957247,0.836171,0.930962,0.875755,0.973729,8.381099e-01,0.898757,0.866584,0.973444
3,9.356422e-01,0.821879,0.655849,0.000000,9.681958e-01,0.931956,0.908770,0.811940,0.898716,0.939141,...,0.947893,0.963216,0.866885,0.806529,0.853942,0.969862,8.031418e-01,0.847959,0.829914,0.941248
4,6.215248e-01,0.927021,0.978755,0.968196,1.110223e-16,0.762714,0.626400,0.751070,0.943153,0.798573,...,0.661206,0.919420,0.905076,0.920221,0.851393,0.928541,7.600453e-01,0.860405,0.847503,0.686059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,8.819047e-01,0.771417,0.973729,0.969862,9.285415e-01,0.888148,0.892973,0.904102,0.960148,0.928540,...,0.933961,0.568846,0.741979,0.773551,0.567334,0.000000,9.123129e-01,0.819971,0.956736,0.855750
939,6.859280e-01,0.773210,0.838110,0.803142,7.600453e-01,0.647551,0.670075,0.753117,0.879505,0.657039,...,0.672847,0.892976,0.812464,0.818683,0.824842,0.912313,2.220446e-16,0.854848,0.738624,0.758972
940,8.513831e-01,0.838515,0.898757,0.847959,8.604049e-01,0.855554,0.940007,0.853855,0.856755,0.909695,...,0.953048,0.796699,0.711682,0.765789,0.686600,0.819971,8.548477e-01,0.000000,0.898358,0.904880
941,8.204921e-01,0.827732,0.866584,0.829914,8.475026e-01,0.682672,0.717997,0.824678,0.907503,0.787670,...,0.773560,0.926487,0.910412,0.870446,0.900615,0.956736,7.386238e-01,0.898358,0.000000,0.817535
942,6.018253e-01,0.894202,0.973444,0.941248,6.860592e-01,0.723958,0.605636,0.700191,0.924383,0.778140,...,0.736209,0.789237,0.856747,0.922207,0.797756,0.855750,7.589723e-01,0.904880,0.817535,0.000000

In [20]:
# Find  similarity user for 34 using cosine table
similar_input_user=user_sim_table[input_user].sort_values (ascending=True).head(5).index

In [21]:
similar_input_user

Index([34, 450, 852, 811, 509], dtype='int64')

# Convert into list

In [22]:
similar_user_input=list(similar_input_user)

# Using similar_user_input can select movie id from rating table

In [23]:
similar_user_movieid_list=[]
for sim_user in similar_user_input:
    sim=list(rating[rating['user_id']==sim_user]['movie_id'])
    similar_user_movieid_list.append(sim)

In [24]:
len(similar_user_movieid_list)

5

# Convert all the list as single

In [25]:
import itertools
similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))

In [26]:
len(similar_user_movieid_single_list)

663

# Unique movied from the list

In [27]:
unique_movieid_similar_user=set(similar_user_movieid_single_list)

In [28]:
len(unique_movieid_similar_user)

590

# Input user watched movie_list

In [29]:
input_user_watched_movieid=list(rating[rating['user_id']==input_user]['movie_id'].values)

In [30]:
input_user_watched_movieid

[np.int64(312),
 np.int64(242),
 np.int64(690),
 np.int64(310),
 np.int64(259),
 np.int64(299),
 np.int64(245),
 np.int64(332),
 np.int64(329),
 np.int64(286),
 np.int64(1024),
 np.int64(324),
 np.int64(294),
 np.int64(292),
 np.int64(990),
 np.int64(289),
 np.int64(898),
 np.int64(899),
 np.int64(288),
 np.int64(991)]

# Create a list which should have recommendation movieid to the input user

In [31]:
recom=[]
for per_id in unique_movieid_similar_user:
    if (per_id in input_user_watched_movieid):
        pass
    else:
        recom.append(per_id)

In [32]:
len(recom)

570

In [33]:
sorted(recom)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 243,
 250,
 252,
 254,
 257,
 258,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 277,
 278,
 280,
 281,
 282,
 283,
 284,
 287,
 290,
 300,
 301,
 302,
 304,
 305,
 307,
 308,
 309,
 311,
 313,
 315,
 316,
 318,
 319,
 321,
 322,
 323,
 326,
 328,
 336,
 338,
 340,
 343,
 345,
 347,
 354,
 356,
 357,
 358,
 366,
 367,
 371,
 372,
 373,
 378,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 392,
 393,
 395,
 396,
 399,
 400,
 401,
 402,
 403,
 405,
 407,
 408,
 414,
 415,
 416,
 417,
 418,
 419,
 421,
 422,
 423,
 427,
 428,
 430,
 431,
 432,
 433,
 434,
 435,
 443,
 448,
 451,
 455,
 457,
 462,
 465,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 509,
 510,
 511,
 514,
 515,
 516,
 518,
 519,
 520,
 521,
 523,
 525,
 526,
 527,
 528,
 530,
 535,
 546,
 549,
 550,
 553,
 557,
 558,
 559,
 561,
 566,
 568,
 570,
 571,
 582,
 583,
 584,
 588,
 589,
 591,
 597,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 616,
 618,
 619,
 620,
 622,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 637,
 642,
 647,
 648,
 650,
 651,
 654,
 655,
 657,
 659,
 660,
 661,
 662,
 663,
 671,
 673,
 678,
 679,
 680,
 681,
 685,
 686,
 687,
 689,
 692,
 693,
 696,
 699,
 700,
 702,
 704,
 705,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 722,
 723,
 724,
 725,
 727,
 728,
 729,
 731,
 732,
 734,
 735,
 736,
 739,
 741,
 742,
 747,
 748,
 749,
 750,
 751,
 754,
 756,
 761,
 762,
 765,
 771,
 774,
 775,
 776,
 778,
 781,
 783,
 785,
 790,
 792,
 794,
 795,
 801,
 807,
 812,
 815,
 820,
 821,
 823,
 825,
 826,
 827,
 832,
 837,
 840,
 841,
 842,
 845,
 846,
 847,
 865,
 866,
 869,
 873,
 878,
 879,
 892,
 895,
 900,
 901,
 902,
 904,
 905,
 908,
 921,
 923,
 926,
 928,
 930,
 934,
 936,
 939,
 940,
 942,
 951,
 956,
 965,
 966,
 967,
 968,
 969,
 988,
 1020,
 1028,
 1030,
 1033,
 1036,
 1037,
 1039,
 1041,
 1044,
 1047,
 1048,
 1050,
 1052,
 1053,
 1054,
 1061,
 1091,
 1092,
 1107,
 1112,
 1115,
 1116,
 1119,
 1126,
 1135,
 1140,
 1147,
 1152,
 1153,
 1160,
 1163,
 1172,
 1184,
 1192,
 1197,
 1203,
 1208,
 1212,
 1220,
 1221,
 1222,
 1226,
 1248,
 1249,
 1261,
 1263,
 1269,
 1271,
 1282,
 1284,
 1286,
 1297,
 1303,
 1311,
 1401,
 1402,
 1421,
 1425,
 1435,
 1441,
 1444,
 1446,
 1479,
 1480,
 1490,
 1518,
 1521,
 1603,
 1615]

In [34]:
# Cross Checking 
sorted(unique_movieid_similar_user)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 242,
 243,
 245,
 250,
 252,
 254,
 257,
 258,
 259,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 277,
 278,
 280,
 281,
 282,
 283,
 284,
 286,
 287,
 288,
 289,
 290,
 292,
 294,
 299,
 300,
 301,
 302,
 304,
 305,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 315,
 316,
 318,
 319,
 321,
 322,
 323,
 324,
 326,
 328,
 329,
 332,
 336,
 338,
 340,
 343,
 345,
 347,
 354,
 356,
 357,
 358,
 366,
 367,
 371,
 372,
 373,
 378,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 392,
 393,
 395,
 396,
 399,
 400,
 401,
 402,
 403,
 405,
 407,
 408,
 414,
 415,
 416,
 417,
 418,
 419,
 421,
 422,
 423,
 427,
 428,
 430,
 431,
 432,
 433,
 434,
 435,
 443,
 448,
 451,
 455,
 457,
 462,
 465,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 509,
 510,
 511,
 514,
 515,
 516,
 518,
 519,
 520,
 521,
 523,
 525,
 526,
 527,
 528,
 530,
 535,
 546,
 549,
 550,
 553,
 557,
 558,
 559,
 561,
 566,
 568,
 570,
 571,
 582,
 583,
 584,
 588,
 589,
 591,
 597,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 616,
 618,
 619,
 620,
 622,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 637,
 642,
 647,
 648,
 650,
 651,
 654,
 655,
 657,
 659,
 660,
 661,
 662,
 663,
 671,
 673,
 678,
 679,
 680,
 681,
 685,
 686,
 687,
 689,
 690,
 692,
 693,
 696,
 699,
 700,
 702,
 704,
 705,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 722,
 723,
 724,
 725,
 727,
 728,
 729,
 731,
 732,
 734,
 735,
 736,
 739,
 741,
 742,
 747,
 748,
 749,
 750,
 751,
 754,
 756,
 761,
 762,
 765,
 771,
 774,
 775,
 776,
 778,
 781,
 783,
 785,
 790,
 792,
 794,
 795,
 801,
 807,
 812,
 815,
 820,
 821,
 823,
 825,
 826,
 827,
 832,
 837,
 840,
 841,
 842,
 845,
 846,
 847,
 865,
 866,
 869,
 873,
 878,
 879,
 892,
 895,
 898,
 899,
 900,
 901,
 902,
 904,
 905,
 908,
 921,
 923,
 926,
 928,
 930,
 934,
 936,
 939,
 940,
 942,
 951,
 956,
 965,
 966,
 967,
 968,
 969,
 988,
 990,
 991,
 1020,
 1024,
 1028,
 1030,
 1033,
 1036,
 1037,
 1039,
 1041,
 1044,
 1047,
 1048,
 1050,
 1052,
 1053,
 1054,
 1061,
 1091,
 1092,
 1107,
 1112,
 1115,
 1116,
 1119,
 1126,
 1135,
 1140,
 1147,
 1152,
 1153,
 1160,
 1163,
 1172,
 1184,
 1192,
 1197,
 1203,
 1208,
 1212,
 1220,
 1221,
 1222,
 1226,
 1248,
 1249,
 1261,
 1263,
 1269,
 1271,
 1282,
 1284,
 1286,
 1297,
 1303,
 1311,
 1401,
 1402,
 1421,
 1425,
 1435,
 1441,
 1444,
 1446,
 1479,
 1480,
 1490,
 1518,
 1521,
 1603,
 1615]

In [35]:
# Cross Checking
sorted(input_user_watched_movieid)

[np.int64(242),
 np.int64(245),
 np.int64(259),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(690),
 np.int64(898),
 np.int64(899),
 np.int64(990),
 np.int64(991),
 np.int64(1024)]

In [36]:
# Checking the common movie list
list(set(unique_movieid_similar_user)&set(input_user_watched_movieid))

[np.int64(1024),
 np.int64(898),
 np.int64(259),
 np.int64(899),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(690),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(990),
 np.int64(991),
 np.int64(242),
 np.int64(245)]

In [37]:
user_pred=pd.DataFrame(user_prediction)

In [38]:
user_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.065326,0.734303,0.629924,1.010669,0.640686,0.476150,1.784569,1.163032,1.513350,0.704478,...,0.394041,0.394434,0.393981,0.392972,0.393344,0.392272,0.394909,0.393590,0.393049,0.392771
1,1.763088,0.384040,0.196179,0.731538,0.225643,0.003892,1.493597,0.876153,1.108467,0.261991,...,-0.086942,-0.085491,-0.087137,-0.088158,-0.087298,-0.089288,-0.087468,-0.088378,-0.086918,-0.086712
2,1.795904,0.329047,0.158829,0.684154,0.173277,-0.035621,1.488230,0.835769,1.135426,0.236383,...,-0.134795,-0.133537,-0.135543,-0.136438,-0.135041,-0.137611,-0.136374,-0.136992,-0.134969,-0.134765
3,1.729951,0.293913,0.127741,0.644932,0.142143,-0.062261,1.437010,0.796249,1.096663,0.211789,...,-0.161413,-0.160220,-0.161542,-0.162586,-0.161634,-0.163877,-0.162283,-0.163080,-0.161442,-0.161248
4,1.796651,0.454474,0.354422,0.763130,0.359539,0.195987,1.547370,0.908904,1.292027,0.437954,...,0.101762,0.102405,0.101923,0.100839,0.101711,0.099951,0.102515,0.101233,0.101075,0.101201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.676950,0.346339,0.177518,0.689906,0.199740,0.003297,1.429565,0.830905,1.070986,0.262183,...,-0.092434,-0.091197,-0.092851,-0.093801,-0.092953,-0.094539,-0.092217,-0.093378,-0.092686,-0.092423
939,1.822346,0.419125,0.286430,0.715605,0.294442,0.106633,1.514591,0.853050,1.195304,0.359260,...,0.014060,0.014688,0.014123,0.013060,0.013669,0.011978,0.014065,0.013021,0.013639,0.013796
940,1.591515,0.275269,0.102195,0.624383,0.133762,-0.069553,1.320734,0.765529,1.035088,0.192697,...,-0.166179,-0.164981,-0.166278,-0.167392,-0.166679,-0.168486,-0.166217,-0.167352,-0.166575,-0.166414
941,1.810363,0.404799,0.275450,0.726616,0.281316,0.087068,1.550310,0.850057,1.205745,0.342987,...,-0.008362,-0.007757,-0.008225,-0.009218,-0.008232,-0.010138,-0.008009,-0.009074,-0.008466,-0.008049
942,1.838431,0.479648,0.384963,0.780521,0.388442,0.240998,1.564232,0.946704,1.289865,0.487383,...,0.147027,0.148208,0.147193,0.146199,0.146916,0.145539,0.148194,0.146867,0.146298,0.146415

In [39]:
user_pred_trans=user_pred.T

In [40]:
user_pred_trans

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.065326,1.763088,1.795904,1.729951,1.796651,1.996889,2.466055,1.693486,1.681165,2.021688,...,1.924844,1.619096,1.891812,1.696368,1.717658,1.676950,1.822346,1.591515,1.810363,1.838431
1,0.734303,0.384040,0.329047,0.293913,0.454474,0.651172,1.099186,0.296285,0.279528,0.650911,...,0.552456,0.311680,0.550513,0.322611,0.431368,0.346339,0.419125,0.275269,0.404799,0.479648
2,0.629924,0.196179,0.158829,0.127741,0.354422,0.528276,1.016489,0.195398,0.121887,0.530669,...,0.451194,0.140613,0.354913,0.144344,0.247851,0.177518,0.286430,0.102195,0.275450,0.384963
3,1.010669,0.731538,0.684154,0.644932,0.763130,0.921054,1.362861,0.612075,0.616094,0.916215,...,0.834176,0.661829,0.893214,0.662304,0.783208,0.689906,0.715605,0.624383,0.726616,0.780521
4,0.640686,0.225643,0.173277,0.142143,0.359539,0.537388,1.006458,0.198638,0.136368,0.531720,...,0.455212,0.166992,0.398759,0.167841,0.283796,0.199740,0.294442,0.133762,0.281316,0.388442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.392272,-0.089288,-0.137611,-0.163877,0.099951,0.259848,0.764340,-0.072866,-0.163505,0.263527,...,0.185602,-0.128949,0.095681,-0.143177,-0.009425,-0.094539,0.011978,-0.168486,-0.010138,0.145539
1678,0.394909,-0.087468,-0.136374,-0.162283,0.102515,0.262375,0.766967,-0.070435,-0.161425,0.266037,...,0.188059,-0.126624,0.097792,-0.141018,-0.007085,-0.092217,0.014065,-0.166217,-0.008009,0.148194
1679,0.393590,-0.088378,-0.136992,-0.163080,0.101233,0.261111,0.765654,-0.071651,-0.162465,0.264782,...,0.186831,-0.127786,0.096736,-0.142097,-0.008255,-0.093378,0.013021,-0.167352,-0.009074,0.146867
1680,0.393049,-0.086918,-0.134969,-0.161442,0.101075,0.261061,0.764983,-0.071744,-0.161396,0.264589,...,0.186850,-0.127045,0.097826,-0.140977,-0.007621,-0.092686,0.013639,-0.166575,-0.008466,0.146298
1681,0.392771,-0.086712,-0.134765,-0.161248,0.101201,0.261089,0.765165,-0.071357,-0.161430,0.264781,...,0.186858,-0.126812,0.097654,-0.140965,-0.007369,-0.092423,0.013796,-0.166414,-0.008049,0.146415

In [41]:
user_pred_trans[34]

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [42]:
gg=user_pred_trans[34]

In [43]:
gg

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [44]:
g=pd.DataFrame(gg)

In [45]:
g

            34
0     1.740469
1     0.283366
2     0.114987
3     0.645096
4     0.127844
...        ...
1677 -0.183977
1678 -0.182367
1679 -0.183172
1680 -0.181400
1681 -0.181306

[1682 rows x 1 columns]

In [46]:
s=g.T

In [47]:
s

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
34,1.740469,0.283366,0.114987,0.645096,0.127844,-0.081329,1.448638,0.794313,1.08901,0.194232,...,-0.181256,-0.180156,-0.181837,-0.182819,-0.181432,-0.183977,-0.182367,-0.183172,-0.1814,-0.181306

In [48]:
s[187].values>0.4

array([ True])

# From recommendation list select hightest rated film which would like by the user. Based on user prediction

In [49]:
highest_user=[]
input_user_pre=pd.DataFrame(user_pred_trans[input_user])
input_user_pred=input_user_pre.T
for re in recom:
    value=input_user_pred[re].values
    if(value>=1):
        highest_user.append(re)

In [50]:
len(highest_user)

27

# Now we give movieid respective movie list

In [62]:
i_cols=['movie id','movie title','release date','video release date','imdb url','unknown','action','animation','children',
        'comedy','crime','document','drama','fantasy','film_noie','horror','musical','mystery','romance','sci_fi','thriller','war','western']
items=pd.read_csv('ml-100k/u.item',sep='|',names=i_cols,encoding='latin-1')

# Creating movie list based on recommendation movieid

In [63]:
movie_title=[]
for movieid in highest_user:
    mov=items[items['movie id']==movieid]['movie title'].values
    movie_title.append(mov)

In [64]:
movie_title

[array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object),
 array([], dtype=object)]

In [55]:
# Converting into whole list 
import itertools 
final_recom_movie=list (itertools.chain.from_iterable(movie_title))

In [ ]:
final_recom_movie